language: ruby

rvm:
  - 1.9.3

branches:
 only:
 - master

notifications:
 email: false

install: ./.travis.sh install

before_script: ./.travis.sh migrate

script: 
 - gem install rubocop -v 0.35.1 && rubocop
 - cd ../foreman
 - rake test:fusor

services:
  - postgresql
