:fusor:
  :content:
    :content_view:
      :composite_view_name: "Fusor Deployment Content"
      :rpm_component_view_name: "Fusor RPM Content"
      :puppet_component_view_name: "Fusor Puppet Content"

    :rhev:
      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Linux Server"
        :repository_set_name: "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Hypervisor (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "Red Hat Enterprise Virtualization"
        :repository_set_name: "Red Hat Enterprise Virtualization Manager 3.5 (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"

      - :product_name: "JBoss Enterprise Application Platform"
        :repository_set_name: "JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)"
        :basearch: "x86_64"
        :releasever: "6Server"
